#!/bin/bash
# Blocks writes to build artifacts, binary files, and dependency directories.
# Used as a PreToolUse hook for Edit|Write operations.
# Exit 2 = block the action. Exit 0 = allow.

INPUT=$(cat)
_PY=""
_pycand=$(command -v python3 2>/dev/null || command -v python 2>/dev/null || true)
if [ -n "$_pycand" ] && printf '' | "$_pycand" -c "pass" >/dev/null 2>&1; then
  _PY="$_pycand"
fi
if [ -n "$_PY" ]; then
  FILE_PATH=$(printf '%s' "$INPUT" | "$_PY" -c \
    "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('file_path',''))" \
    2>/dev/null || true)
else
  FILE_PATH=$(printf '%s' "$INPUT" \
    | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' \
    | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)"/\1/' \
    | head -1 || true)
fi

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Block dependency and build directories
case "$FILE_PATH" in
  node_modules/*|*/node_modules/*)
    REASON="Cannot write into node_modules/. Install dependencies via package manager instead." ;;
  vendor/*|*/vendor/*)
    REASON="Cannot write into vendor/. Use dependency manager instead." ;;
  dist/*|*/dist/*|build/*|*/build/*|.next/*|*/.next/*)
    REASON="Cannot write into build output directories. These are generated by the build process." ;;
  __pycache__/*|*/__pycache__/*)
    REASON="Cannot write into __pycache__/. These are generated by Python." ;;
  .venv/*|*/.venv/*|venv/*|*/venv/*)
    REASON="Cannot write into virtual environment directories." ;;
  *)
    REASON="" ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

# Block binary and archive file extensions
BASENAME=$(basename "$FILE_PATH")
case "$BASENAME" in
  *.wasm|*.so|*.dylib|*.dll|*.exe|*.o|*.a)
    REASON="Cannot write binary files. These should be compiled, not hand-written." ;;
  *.zip|*.tar|*.tar.gz|*.tar.bz2|*.tgz|*.rar|*.7z)
    REASON="Cannot write archive files." ;;
  *.mp4|*.mov|*.avi|*.mkv|*.mp3|*.wav|*.flac)
    REASON="Cannot write media files. Add these manually outside Claude Code." ;;
  *.pyc|*.pyo|*.class)
    REASON="Cannot write compiled bytecode files." ;;
esac

if [ -n "$REASON" ]; then
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"$REASON\"}}"
  exit 2
fi

exit 0