import type { DefaultTheme } from 'styled-components'

const v = (name: string) => `var(${name})` as const

export const theme: DefaultTheme = {
  colors: {
    primary: {
      50: v('--color-primary-50'),
      100: v('--color-primary-100'),
      200: v('--color-primary-200'),
      300: v('--color-primary-300'),
      400: v('--color-primary-400'),
      500: v('--color-primary-500'),
      600: v('--color-primary-600'),
      700: v('--color-primary-700'),
      800: v('--color-primary-800'),
      900: v('--color-primary-900'),
    },
    neutral: {
      50: v('--color-neutral-50'),
      100: v('--color-neutral-100'),
      200: v('--color-neutral-200'),
      300: v('--color-neutral-300'),
      400: v('--color-neutral-400'),
      500: v('--color-neutral-500'),
      600: v('--color-neutral-600'),
      700: v('--color-neutral-700'),
      800: v('--color-neutral-800'),
      900: v('--color-neutral-900'),
    },
    success: {
      50: v('--color-success-50'),
      bg: v('--color-success-bg'),
      border: v('--color-success-border'),
      fg: v('--color-success-fg'),
      base: v('--color-success'),
      fgOn: v('--color-success-fg-on'),
    },
    warning: {
      50: v('--color-warning-50'),
      bg: v('--color-warning-bg'),
      border: v('--color-warning-border'),
      fg: v('--color-warning-fg'),
      base: v('--color-warning'),
      fgOn: v('--color-warning-fg-on'),
    },
    error: {
      50: v('--color-error-50'),
      bg: v('--color-error-bg'),
      border: v('--color-error-border'),
      fg: v('--color-error-fg'),
      base: v('--color-error'),
      fgOn: v('--color-error-fg-on'),
    },
    info: {
      50: v('--color-info-50'),
      bg: v('--color-info-bg'),
      border: v('--color-info-border'),
      fg: v('--color-info-fg'),
      base: v('--color-info'),
      fgOn: v('--color-info-fg-on'),
    },
    bg: {
      page: v('--color-bg-page'),
      card: v('--color-bg-card'),
      elevated: v('--color-bg-elevated'),
      overlay: v('--color-bg-overlay'),
      inverse: v('--color-bg-inverse'),
      secondary: v('--color-bg-secondary'),
    },
    text: {
      primary: v('--color-text-primary'),
      secondary: v('--color-text-secondary'),
      muted: v('--color-text-muted'),
      disabled: v('--color-text-disabled'),
      inverse: v('--color-text-inverse'),
      strong: v('--color-text-strong'),
      link: v('--color-text-link'),
      linkHover: v('--color-text-link-hover'),
    },
    border: {
      subtle: v('--color-border-subtle'),
      default: v('--color-border-default'),
      strong: v('--color-border-strong'),
      focus: v('--color-border-focus'),
    },
  },
  spacing: {
    0: v('--space-0'),
    1: v('--space-1'),
    2: v('--space-2'),
    3: v('--space-3'),
    4: v('--space-4'),
    5: v('--space-5'),
    6: v('--space-6'),
    8: v('--space-8'),
    10: v('--space-10'),
    12: v('--space-12'),
    16: v('--space-16'),
    20: v('--space-20'),
    24: v('--space-24'),
    32: v('--space-32'),
  },
  radii: {
    sm: v('--radius-sm'),
    md: v('--radius-md'),
    lg: v('--radius-lg'),
    xl: v('--radius-xl'),
    '2xl': v('--radius-2xl'),
    full: v('--radius-full'),
  },
  shadows: {
    elevation1: v('--shadow-elevation-1'),
    elevation2: v('--shadow-elevation-2'),
    elevation3: v('--shadow-elevation-3'),
    elevation4: v('--shadow-elevation-4'),
    focusRing: v('--shadow-focus-ring'),
  },
  zIndex: {
    dropdown: v('--z-dropdown'),
    sticky: v('--z-sticky'),
    fixed: v('--z-fixed'),
    modalBackdrop: v('--z-modal-backdrop'),
    modal: v('--z-modal'),
    popover: v('--z-popover'),
    toast: v('--z-toast'),
    tooltip: v('--z-tooltip'),
  },
  // Raw px strings — used in @media (min-width: ${theme.breakpoints.md}). var(--bp-*) does NOT
  // resolve inside @media queries, so we keep these as literal strings (single source still tokens.css).
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
  motion: {
    duration: {
      instant: v('--duration-instant'),
      fast: v('--duration-fast'),
      base: v('--duration-base'),
      slow: v('--duration-slow'),
      slower: v('--duration-slower'),
    },
    easing: {
      out: v('--ease-out'),
      in: v('--ease-in'),
      inOut: v('--ease-in-out'),
      spring: v('--ease-spring'),
    },
  },
  typography: {
    fontFamily: {
      display: v('--font-display'),
      body: v('--font-body'),
      mono: v('--font-mono'),
    },
    type: {
      caption: {
        size: v('--type-caption-size'),
        line: v('--type-caption-line'),
        tracking: v('--type-caption-tracking'),
        weight: v('--type-caption-weight'),
      },
      small: {
        size: v('--type-small-size'),
        line: v('--type-small-line'),
        tracking: v('--type-small-tracking'),
        weight: v('--type-small-weight'),
      },
      body: {
        size: v('--type-body-size'),
        line: v('--type-body-line'),
        tracking: v('--type-body-tracking'),
        weight: v('--type-body-weight'),
      },
      bodyLg: {
        size: v('--type-body-lg-size'),
        line: v('--type-body-lg-line'),
        tracking: v('--type-body-lg-tracking'),
        weight: v('--type-body-lg-weight'),
      },
      h4: {
        size: v('--type-h4-size'),
        line: v('--type-h4-line'),
        tracking: v('--type-h4-tracking'),
        weight: v('--type-h4-weight'),
      },
      h3: {
        size: v('--type-h3-size'),
        line: v('--type-h3-line'),
        tracking: v('--type-h3-tracking'),
        weight: v('--type-h3-weight'),
      },
      h2: {
        size: v('--type-h2-size'),
        line: v('--type-h2-line'),
        tracking: v('--type-h2-tracking'),
        weight: v('--type-h2-weight'),
      },
      h1: {
        size: v('--type-h1-size'),
        line: v('--type-h1-line'),
        tracking: v('--type-h1-tracking'),
        weight: v('--type-h1-weight'),
      },
      display: {
        size: v('--type-display-size'),
        line: v('--type-display-line'),
        tracking: v('--type-display-tracking'),
        weight: v('--type-display-weight'),
      },
    },
    featureNumeric: v('--font-feature-numeric'),
  },
}

export type AppTheme = typeof theme
